services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: testing
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testing
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
